swagger: '2.0'
info:
  version: 0.0.1
  title: SignuTimes API
  description: A simple TSA to get times
  contact:
    email: sobrenombre@gmail.com
host: 'https://signu-tsa.herokuapp.com/'
schemes:
  - http
  - https
basePath: /
paths:
  /:
    get:
      tags:
      summary: Welcome page
      description: Welcome page
      parameters:
      responses:
        '200':
          description: Shows a simple welcome page
  /tsr:
    post:
      summary: It sends a Time Stamp Request (TSR)
      description: If recives a correct Time Stamp Query it will response with a correct TSR
      produces:
        - application/timestamp-reply
      parameters:
        - in: body

      responses:
        '200':
          description: A TSR as binary file
